blog/urls.py
from django.urls import path
from .views import HomeView, PostView, PostCreateView, PostUpdateView, PostDeleteView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import signup, log_in, log_out, profile, edit_profile
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)
from django.urls import reverse_lazy


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='/users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
    path('profile/<username>/', profile, name='profile'),
    path('edit-profile/', edit_profile, name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["username"]


class Profile(models.Model):
    about_me = models.TextField()
    image = models.ImageField(upload_to='profile_image', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")


class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()


class EditProfileForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def clean_username(self):
        """
        This function throws an exception if the username has already been 
        taken by another user
        """

        username = self.cleaned_data['username']
        if username != self.original_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout 
from django.urls import reverse
from .forms import SignUpForm, LoginForm, EditProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import User, Profile


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blog:home')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def log_in(request):
    if request.user.is_authenticated:
        return redirect('blog:home')
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            # Validate if the data is correct
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('blog:home')
            else:
                messages.error(request, 'Invalid email or password')
    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect(reverse('users:login'))


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'users/profile.html', {'profile': profile, 'user': user})

@login_required
def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.user.username, request.POST, request.FILES)
        if form.is_valid():
            about_me = form.cleaned_data["about_me"]
            username = form.cleaned_data["username"]
            image = form.cleaned_data["image"]

            user = User.objects.get(id=request.user.id)
            profile = Profile.objects.get(user=user)
            user.username = username
            user.save()
            profile.about_me = about_me
            if image:
                profile.image = image
            profile.save()
            return redirect("users:profile", username=user.username)
    else:
        form = EditProfileForm(request.user.username)
    return render(request, "users/edit_profile.html", {'form': form})

templates/users/edit_profile.html
{% extends 'base.html' %}

{% block head_title %}Edit profile{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <h2 class="my-5">Edit profile</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ form.username.label_tag }}
          <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
            name="username" value='{{ form.username.value|default:user.username }}'>
          {% if form.username.errors %}
          <div class="invalid-feedback">{{ form.username.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.about_me.label_tag }}
          <textarea type="text" class="form-control {% if form.about_me.errors %}is-invalid{% endif %}" id="id_about_me"
            name="about_me" value='{{ form.about_me.value }}' rows="5"></textarea>
          {% if form.about_me.errors %}
          <div class="invalid-feedback">{{ form.about_me.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.image.label_tag }}<br>
          <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
            accept="image/*">
          {% if form.image.errors %}
          <div class="invalid-feedback">{{ form.image.errors }}</div>
          {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <br>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}

{% block head_title %}Log In{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class=" my-5">Log in</h2>
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.email.label_tag }}
          <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" value='{{ form.email.value|default:"" }}'>
          {% if form.email.errors %}
          <div class="invalid-feedback">{{ form.email.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password.label_tag }}
          <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}"
            id="id_password" name="password" value='{{ form.password.value|default:"" }}'>
          {% if form.password.errors %}
          <div class="invalid-feedback">{{ form.password.errors }}</div>
          {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Login</button>
      </form>
      <br>
      <p>Forgot your password? <a href="{% url 'users:password_reset' %}">Click here</a></p>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_change.html
{% extends 'base.html' %}

{% block head_title %}Change password{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-7">
      <h2 class=" my-5">Change password</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.old_password.label_tag }}
          <input type="password" class="form-control {% if form.old_password.errors %}is-invalid{% endif %}"
            id="id_old_password" name="old_password" value='{{ form.old_password.value|default:"" }}'>
          {% if form.old_password.errors %}
          <div class="invalid-feedback">{{ form.old_password.errors }}</div>
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.new_password1.label_tag }}
          <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
            id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
          {% if form.new_password1.errors %}
          <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
          {% endif %}
          <small class="text-muted">{{ form.new_password1.help_text }}</small>
        </div>
        <div class="form-group">
          {{ form.new_password2.label_tag }}
          <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
            id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
          {% if form.new_password2.errors %}
          <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Change password</button>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_change_done.html
{% extends 'base.html' %}

{% block head_title %}Password changed successfully{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="alert alert-success mt-5" role="alert">
        Your password has been changed successfully!
      </div>
      <a href="{% url 'blog:home' %}" class="btn btn-secondary">Return to home page</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset.html
{% extends 'base.html' %}

{% block head_title %}Password reset{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-4">
      <h2 class=" my-5">Password reset</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.email.label_tag }}
          <input type="email" class="form-control" id="id_email" name="email" value='{{ form.email.value|default:"" }}'>
        </div>

        <button type="submit" class="btn btn-primary">Reset Password</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block head_title %}Password changed successfully{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="my-5">Password Changed successfully</h2>
      <p>
        Your password has been changed successfully. You may now proceed to
        <a href="{% url 'users:login' %}">log in.</a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block head_title %}New password{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class=" my-5">Change password</h2>
      {% if validlink %}
      <div class="row">
        <form class="col-4" method="post">
          {% csrf_token %}
          <div class="form-group">
            {{ form.new_password1.label_tag }}
            <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
              id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
            {% if form.new_password1.errors %}
            <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.new_password2.label_tag }}
            <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
              id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
            {% if form.new_password2.errors %}
            <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">Change password</button>
        </form>
      </div>
      {% else %}
      <p>
        The password reset link was not valid, possibly because it has already been used,
        please request a <a href="{% url 'users:password_reset' %}">new password reset.</a>
      </p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block head_title %}Reset your password{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class=" col-12">
      <h2 class="my-5">Password reset</h2>
      <p>
        We have sent you instructions for setting your password, if an account
        exists with the email you entered you should receive them shortly.
      </p>
      <p>
        If you haven't received an email, make sure you've entered the address you
        signed up with and check your spam folder.
      </p>
    </div>
  </div>
</div>
{% endblock content %}

templates/users/password_reset_email.html
Hello there,

To reset your password for the user {{ user.username }}, click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}


If the above link does not work, please copy and paste the URL into a new window.

Cheers,
The Mini Blog Team

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head_title %}{{ user.username }} | Mini Blog{% endblock head_title %}

{% block content %}
<div class="container-fluid mt-5">
  <div class="row">
    <div class="card col-lg-6 offset-lg-3 mb-3">
      <div class="row">
        {% if user.profile.image %}
        <img class="card-img-top col-sm-3 col-4 my-3" src="{{ profile.image.url }}" alt="{{ user.username }}">
        {% else %}
        <img class="card-img-top col-sm-3 col-4 my-3" src="{% static 'img/avatar.svg' %}" alt="{{ user.username }}">
        {% endif %}
        <div class="card-body col-9">
          <h2 class="card-title my-3">{{ user.username }}</h2>
          <p>Last login on: {{ user.last_login }}</p>
          <p><a href="{% url 'users:edit_profile' %}">Edit your profile</a></p>
          <p><a href="{% url 'users:password_change' %}">Change password</a></p>
          <p class="card-text">{{ user.profile.about_me }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block head_title %}Sign Up{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="my-5">Sign up</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.username.label_tag }}
          <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="id_username"
            name="username" value='{{ form.username.value|default:"" }}'>
          <small class="text-muted">{{ form.username.help_text }}</small>
          {% if form.username.errors %}
          <div class="invalid-feedback">{{ form.username.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
              name="email" value='{{ form.email.value|default:"" }}'>
            {% if form.email.errors %}
            <div class="invalid-feedback">{{ form.email.errors }}</div>
            {% endif %}
          </div>

        <div class="form-group">
          {{ form.password1.label_tag }}
          <input type="password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}"
            id="id_password1" name="password1" value='{{ form.password1.value|default:"" }}'>
          <small class="text-muted">{{ form.password1.help_text }}</small>
          {% if form.password1.errors %}
          <div class="invalid-feedback">{{ form.password1.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password2.label_tag }}
          <input type="password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}"
            id="id_password2" name="password2" value='{{ form.password2.value|default:"" }}'>
          <small class="text-muted">{{ form.password2.help_text }}</small>
          {% if form.password2.errors %}
          <div class="invalid-feedback">{{ form.password2.errors }}</div>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Sign up</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}